# site settings
title: Home
subtitle: 
email: R.Sellevold-1@tudelft.nl
description: PhD Candidate at TU Delft <br /> Ice sheet and global climate interactions
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rsellevold.github.io" # the base hostname & protocol for your site
author: Raymond Sellevold
street_address: Stevinweg 1
city: 2181 CN
state: Delft
zip_code: Zuid-Holland
country: The Netherlands
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/rsellevold
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: http://twitter.com/rsel89

# build settings
markdown: kramdown

sass:
  style: compressed
